-- DBT Model: stg_member_quality_measures
-- Database: dev_dtx_gc
-- Schema: staging
-- Alias: stg_member_quality_measures



WITH fact_member_quality_measures AS (
	--QM1
	SELECT
		memberid,
		1 AS qmid,
		numerator,
		denominator,
		participatingprovidernpi,
		orderingprovidernpi,
		orderingprovider,
		perf_period_key,
		contextdate,
		episode_start_date,
		episode_end_date,
		tin,
		principalcancercode,
		cancerdiagnosisgroupcode,
		treatmentplanpathwayregimenindicatorcode,
		NULL AS icd10code,
		NULL AS icd10description,
		NULL AS claimlinehealthservicecode,
		NULL AS ipdate,
		NULL AS eddate,
		TO_VARCHAR(chemodates) AS chemodate,
		NULL AS chemocode,
		NULL AS consolidated_emetic_desc,
		NULL AS chemodesc,
		NULL AS hospicedate,
		drugsadministered,
		TO_VARCHAR(chemodates) AS drugsadministereddates,
		denominatortriggerdate,
		numeratortriggerdate,
		health_condition,
		authrequestdate,
		authidreference,
		NULL AS daysinhospice,
		NULL AS ht3_desc,
		NULL AS cort_desc,
		NULL AS dop_desc,
		NULL AS nk1_desc,
		NULL AS olz_desc,
		lineofbusiness,
		clinicalscenariodescription,
		dosingdeviationtext,
		biomarkercodedescription
	FROM dev_dtx_gc.staging.stg_qm1

	--QM2a    
	UNION ALL
	SELECT
		memberid,
		10 AS qmid,
		q.low_risk_numerator AS numerator,
		denominator,
		participatingprovidernpi,
		NULL AS orderingprovidernpi,
		NULL AS orderingprovider,
		perf_period_key,
		contextdate,
		episode_start_date,
		episode_end_date,
		tin,
		principalcancercode,
		cancerdiagnosisgroupcode,
		NULL AS treatmentplanpathwayregimenindicatorcode,
		NULL AS icd10code,
		NULL AS icd10description,
		NULL AS claimlinehealthservicecode,
		NULL AS ipdate,
		NULL AS eddate,
		chemodate,
		chemocode,
		consolidated_emetic_desc,
		NULL AS chemodesc,
		NULL AS hospicedate,
		drugsadministered,
		drugsadministereddates,
		NULL AS denominatortriggerdate,
		NULL AS numeratortriggerdate,
		NULL AS health_condition,
		NULL AS authrequestdate,
		NULL AS authidreference,
		NULL AS daysinhospice,
		ht3_desc,
		cort_desc,
		dop_desc,
		nk1_desc,
		olz_desc,
		lineofbusiness,
		NULL AS clinicalscenariodescription,
		NULL AS dosingdeviationtext,
		NULL AS biomarkercodedescription
	FROM dev_dtx_gc.staging.stg_qm2 AS q
	WHERE max_emetic_risk = 1

	--QM2b     
	UNION ALL
	SELECT
		memberid,
		11 AS qmid,
		q.moderate1_risk_numerator AS numerator,
		denominator,
		participatingprovidernpi,
		NULL AS orderingprovidernpi,
		NULL AS orderingprovider,
		perf_period_key,
		contextdate,
		episode_start_date,
		episode_end_date,
		tin,
		principalcancercode,
		cancerdiagnosisgroupcode,
		NULL AS treatmentplanpathwayregimenindicatorcode,
		NULL AS icd10code,
		NULL AS icd10description,
		NULL AS claimlinehealthservicecode,
		NULL AS ipdate,
		NULL AS eddate,
		chemodate,
		chemocode,
		consolidated_emetic_desc,
		NULL AS chemodesc,
		NULL AS hospicedate,
		drugsadministered,
		drugsadministereddates,
		NULL AS denominatortriggerdate,
		NULL AS numeratortriggerdate,
		NULL AS health_condition,
		NULL AS authrequestdate,
		NULL AS authidreference,
		NULL AS daysinhospice,
		ht3_desc,
		cort_desc,
		dop_desc,
		nk1_desc,
		olz_desc,
		lineofbusiness,
		NULL AS clinicalscenariodescription,
		NULL AS dosingdeviationtext,
		NULL AS biomarkercodedescription
	FROM dev_dtx_gc.staging.stg_qm2 AS q
	WHERE max_emetic_risk = 2

	--QM2c   
	UNION ALL
	SELECT
		memberid,
		12 AS qmid,
		q.moderate2_risk_numerator AS numerator,
		denominator,
		participatingprovidernpi,
		NULL AS orderingprovidernpi,
		NULL AS orderingprovider,
		perf_period_key,
		contextdate,
		episode_start_date,
		episode_end_date,
		tin,
		principalcancercode,
		cancerdiagnosisgroupcode,
		NULL AS treatmentplanpathwayregimenindicatorcode,
		NULL AS icd10code,
		NULL AS icd10description,
		NULL AS claimlinehealthservicecode,
		NULL AS ipdate,
		NULL AS eddate,
		chemodate,
		chemocode,
		consolidated_emetic_desc,
		NULL AS chemodesc,
		NULL AS hospicedate,
		drugsadministered,
		drugsadministereddates,
		NULL AS denominatortriggerdate,
		NULL AS numeratortriggerdate,
		NULL AS health_condition,
		NULL AS authrequestdate,
		NULL AS authidreference,
		NULL AS daysinhospice,
		ht3_desc,
		cort_desc,
		dop_desc,
		nk1_desc,
		olz_desc,
		lineofbusiness,
		NULL AS clinicalscenariodescription,
		NULL AS dosingdeviationtext,
		NULL AS biomarkercodedescription
	FROM dev_dtx_gc.staging.stg_qm2 AS q
	WHERE max_emetic_risk = 3

	--QM2d   
	UNION ALL
	SELECT
		memberid,
		13 AS qmid,
		q.high_risk_numerator AS numerator,
		denominator,
		participatingprovidernpi,
		NULL AS orderingprovidernpi,
		NULL AS orderingprovider,
		perf_period_key,
		contextdate,
		episode_start_date,
		episode_end_date,
		tin,
		principalcancercode,
		cancerdiagnosisgroupcode,
		NULL AS treatmentplanpathwayregimenindicatorcode,
		NULL AS icd10code,
		NULL AS icd10description,
		NULL AS claimlinehealthservicecode,
		NULL AS ipdate,
		NULL AS eddate,
		chemodate,
		chemocode,
		consolidated_emetic_desc,
		NULL AS chemodesc,
		NULL AS hospicedate,
		drugsadministered,
		drugsadministereddates,
		NULL AS denominatortriggerdate,
		NULL AS numeratortriggerdate,
		NULL AS health_condition,
		NULL AS authrequestdate,
		NULL AS authidreference,
		NULL AS daysinhospice,
		ht3_desc,
		cort_desc,
		dop_desc,
		nk1_desc,
		olz_desc,
		lineofbusiness,
		NULL AS clinicalscenariodescription,
		NULL AS dosingdeviationtext,
		NULL AS biomarkercodedescription
	FROM dev_dtx_gc.staging.stg_qm2 AS q
	WHERE max_emetic_risk = 4

	--QM3    
	UNION ALL
	SELECT
		memberid,
		3 AS qmid,
		numerator,
		denominator,
		participatingprovidernpi,
		NULL AS orderingprovidernpi,
		NULL AS orderingprovider,
		perf_period_key,
		contextdate,
		episode_start_date,
		episode_end_date,
		tin,
		principalcancercode,
		cancerdiagnosisgroupcode,
		NULL AS treatmentplanpathwayregimenindicatorcode,
		icd10code,
		icd10description,
		claimlinehealthservicecode,
		dateofservice AS ipdate,
		NULL AS eddate,
		TO_CHAR(chemodate) AS chemodate,
		chemocode,
		NULL AS consolidated_emetic_desc,
		chemodesc,
		NULL AS hospicedate,
		NULL AS drugsadministered,
		NULL AS drugsadministereddates,
		chemodate AS denominatortriggerdate,
		CASE WHEN numerator = '1.0' THEN dateofservice END AS numeratortriggerdate,
		NULL AS health_condition,
		NULL AS authrequestdate,
		NULL AS authidreference,
		NULL AS daysinhospice,
		NULL AS ht3_desc,
		NULL AS cort_desc,
		NULL AS dop_desc,
		NULL AS nk1_desc,
		NULL AS olz_desc,
		lineofbusiness,
		NULL AS clinicalscenariodescription,
		NULL AS dosingdeviationtext,
		NULL AS biomarkercodedescription
	FROM dev_dtx_gc.staging.stg_qm3_4
	WHERE qm_name = 'QM3'

	--QM4    
	UNION ALL
	SELECT
		memberid,
		4 AS qmid,
		numerator,
		denominator,
		participatingprovidernpi,
		NULL AS orderingprovidernpi,
		NULL AS orderingprovider,
		perf_period_key,
		contextdate,
		episode_start_date,
		episode_end_date,
		tin,
		principalcancercode,
		cancerdiagnosisgroupcode,
		NULL AS treatmentplanpathwayregimenindicatorcode,
		icd10code,
		icd10description,
		claimlinehealthservicecode,
		NULL AS ipdate,
		dateofservice AS eddate,
		TO_CHAR(chemodate) AS chemodate,
		chemocode,
		NULL AS consolidated_emetic_desc,
		chemodesc,
		NULL AS hospicedate,
		NULL AS drugsadministered,
		NULL AS drugsadministereddates,
		chemodate AS denominatortriggerdate,
		CASE WHEN numerator = '1.0' THEN dateofservice END AS numeratortriggerdate,
		NULL AS health_condition,
		NULL AS authrequestdate,
		NULL AS authidreference,
		NULL AS daysinhospice,
		NULL AS ht3_desc,
		NULL AS cort_desc,
		NULL AS dop_desc,
		NULL AS nk1_desc,
		NULL AS olz_desc,
		lineofbusiness,
		NULL AS clinicalscenariodescription,
		NULL AS dosingdeviationtext,
		NULL AS biomarkercodedescription
	FROM dev_dtx_gc.staging.stg_qm3_4
	WHERE qm_name = 'QM4'

	--QM5    
	UNION ALL

	SELECT
		memberid,
		5 AS qmid,
		numerator,
		denominator,
		participatingprovidernpi,
		NULL AS orderingprovidernpi,
		NULL AS orderingprovider,
		perf_period_key,
		contextdate,
		episode_start_date,
		episode_end_date,
		tin,
		principalcancercode,
		cancerdiagnosisgroupcode,
		NULL AS treatmentplanpathwayregimenindicatorcode,
		NULL AS icd10code,
		NULL AS icd10description,
		NULL AS claimlinehealthservicecode,
		NULL AS ipdate,
		NULL AS eddate,
		TO_CHAR(chemodate) AS chemodate,
		chemocode,
		NULL AS consolidated_emetic_desc,
		NULL AS chemodesc,
		NULL AS hospicedate,
		NULL AS drugsadministered,
		NULL AS drugsadministereddates,
		memberdeathdate AS denominatortriggerdate,
		chemodate AS numeratortriggerdate,
		NULL AS health_condition,
		NULL AS authrequestdate,
		NULL AS authidreference,
		NULL AS daysinhospice,
		NULL AS ht3_desc,
		NULL AS cort_desc,
		NULL AS dop_desc,
		NULL AS nk1_desc,
		NULL AS olz_desc,
		lineofbusiness,
		NULL AS clinicalscenariodescription,
		NULL AS dosingdeviationtext,
		NULL AS biomarkercodedescription
	FROM dev_dtx_gc.staging.stg_qm5

	--QM6   
	UNION ALL
	SELECT
		memberid,
		6 AS qmid,
		numerator,
		denominator,
		participatingprovidernpi,
		NULL AS orderingprovidernpi,
		NULL AS orderingprovider,
		perf_period_key,
		contextdate,
		episode_start_date,
		episode_end_date,
		tin,
		principalcancercode,
		cancerdiagnosisgroupcode,
		NULL AS treatmentplanpathwayregimenindicatorcode,
		NULL AS icd10code,
		NULL AS icd10description,
		NULL AS claimlinehealthservicecode,
		NULL AS ipdate,
		lastedvisitdate AS eddate,
		NULL AS chemodate,
		NULL AS chemocode,
		NULL AS consolidated_emetic_desc,
		NULL AS chemodesc,
		NULL AS hospicedate,
		NULL AS drugsadministered,
		NULL AS drugsadministereddates,
		memberdeathdate AS denominatortriggerdate,
		lastedvisitdate AS numeratortriggerdate,
		NULL AS health_condition,
		NULL AS authrequestdate,
		NULL AS authidreference,
		NULL AS daysinhospice,
		NULL AS ht3_desc,
		NULL AS cort_desc,
		NULL AS dop_desc,
		NULL AS nk1_desc,
		NULL AS olz_desc,
		lineofbusiness,
		NULL AS clinicalscenariodescription,
		NULL AS dosingdeviationtext,
		NULL AS biomarkercodedescription
	FROM dev_dtx_gc.staging.stg_qm6

	--QM7   
	UNION ALL
	SELECT
		memberid,
		7 AS qmid,
		numerator,
		denominator,
		participatingprovidernpi,
		NULL AS orderingprovidernpi,
		NULL AS orderingprovider,
		perf_period_key,
		contextdate,
		episode_start_date,
		episode_end_date,
		tin,
		principalcancercode,
		cancerdiagnosisgroupcode,
		NULL AS treatmentplanpathwayregimenindicatorcode,
		NULL AS icd10code,
		NULL AS icd10description,
		NULL AS claimlinehealthservicecode,
		NULL AS ipdate,
		NULL AS eddate,
		NULL AS chemodate,
		NULL AS chemocode,
		NULL AS consolidated_emetic_desc,
		NULL AS chemodesc,
		NULL AS hospicedate,
		NULL AS drugsadministered,
		NULL AS drugsadministereddates,
		memberdeathdate AS denominatortriggerdate,
		lasticuvisitdate AS numeratortriggerdate,
		NULL AS health_condition,
		NULL AS authrequestdate,
		NULL AS authidreference,
		NULL AS daysinhospice,
		NULL AS ht3_desc,
		NULL AS cort_desc,
		NULL AS dop_desc,
		NULL AS nk1_desc,
		NULL AS olz_desc,
		lineofbusiness,
		NULL AS clinicalscenariodescription,
		NULL AS dosingdeviationtext,
		NULL AS biomarkercodedescription
	FROM dev_dtx_gc.staging.stg_qm7

	--QM8   
	UNION ALL
	SELECT
		memberid,
		8 AS qmid,
		numerator,
		denominator,
		participatingprovidernpi,
		NULL AS orderingprovidernpi,
		NULL AS orderingprovider,
		perf_period_key,
		contextdate,
		episode_start_date,
		episode_end_date,
		tin,
		principalcancercode,
		cancerdiagnosisgroupcode,
		NULL AS treatmentplanpathwayregimenindicatorcode,
		NULL AS icd10code,
		NULL AS icd10description,
		NULL AS claimlinehealthservicecode,
		NULL AS ipdate,
		NULL AS eddate,
		NULL AS chemodate,
		NULL AS chemocode,
		NULL AS consolidated_emetic_desc,
		NULL AS chemodesc,
		hospicedate,
		NULL AS drugsadministered,
		NULL AS drugsadministereddates,
		memberdeathdate AS denominatortriggerdate,
		hospicedate AS numeratortriggerdate,
		NULL AS health_condition,
		NULL AS authrequestdate,
		NULL AS authidreference,
		NULL AS daysinhospice,
		NULL AS ht3_desc,
		NULL AS cort_desc,
		NULL AS dop_desc,
		NULL AS nk1_desc,
		NULL AS olz_desc,
		lineofbusiness,
		NULL AS clinicalscenariodescription,
		NULL AS dosingdeviationtext,
		NULL AS biomarkercodedescription
	FROM dev_dtx_gc.staging.stg_qm8

	--QM9   
	UNION ALL
	SELECT
		memberid,
		9 AS qmid,
		numerator,
		denominator,
		participatingprovidernpi,
		NULL AS orderingprovidernpi,
		NULL AS orderingprovider,
		perf_period_key,
		contextdate,
		episode_start_date,
		episode_end_date,
		tin,
		principalcancercode,
		cancerdiagnosisgroupcode,
		NULL AS treatmentplanpathwayregimenindicatorcode,
		NULL AS icd10code,
		NULL AS icd10description,
		NULL AS claimlinehealthservicecode,
		NULL AS ipdate,
		NULL AS eddate,
		NULL AS chemodate,
		NULL AS chemocode,
		NULL AS consolidated_emetic_desc,
		NULL AS chemodesc,
		lastnohospicedate AS hospicedate,
		NULL AS drugsadministered,
		NULL AS drugsadministereddates,
		memberdeathdate AS denominatortriggerdate,
		lastnohospicedate AS numeratortriggerdate,
		NULL AS health_condition,
		NULL AS authrequestdate,
		NULL AS authidreference,
		daysinhospice,
		NULL AS ht3_desc,
		NULL AS cort_desc,
		NULL AS dop_desc,
		NULL AS nk1_desc,
		NULL AS olz_desc,
		lineofbusiness,
		NULL AS clinicalscenariodescription,
		NULL AS dosingdeviationtext,
		NULL AS biomarkercodedescription
	FROM dev_dtx_gc.staging.stg_qm9
),

stg_member_chemotherapy AS (
	SELECT
		c.memberid,
		DATE_TRUNC('month', chemodate) AS attributionstartdate,
		LISTAGG(DISTINCT chemodate, ', ') WITHIN GROUP (
			ORDER BY chemodate
		) AS chemodate,
		LISTAGG(DISTINCT chemocode, ', ') WITHIN GROUP (
			ORDER BY chemocode
		) AS chemocode
	FROM dev_dtx_gc.staging.stg_member_chemotherapy AS c
	GROUP BY c.memberid, DATE_TRUNC('month', chemodate)
)

SELECT
	fmq.memberid,
	fmq.qmid,
	SUM(fmq.numerator) AS numerator,
	SUM(fmq.denominator) AS denominator,
	fmq.participatingprovidernpi,
	fmq.orderingprovidernpi,
	fmq.orderingprovider,
	fmq.perf_period_key,
	fmq.contextdate,
	fmq.episode_start_date,
	fmq.episode_end_date,
	fmq.tin AS attributedprovidertaxid,
	fmq.principalcancercode,
	fmq.cancerdiagnosisgroupcode,
	CONCAT(COALESCE(fmq.participatingprovidernpi, ''), '_', fmq.tin) AS participatingnpi_attributedtin,
	CONCAT(fmq.memberid, '_', fmq.tin) AS memberid_attributedtin,
	DATE_TRUNC('seconds', SYSDATE()) AS recordinsertiondate_utc,
	fmq.treatmentplanpathwayregimenindicatorcode,
	fmq.icd10description,
	fmq.icd10code,
	fmq.claimlinehealthservicecode,
	fmq.ipdate,
	fmq.eddate,
	CASE WHEN fmq.qmid IN (1, 10, 11, 12, 13, 3, 4, 5) THEN fmq.chemodate ELSE smc.chemodate END AS chemodate,
	CASE WHEN fmq.qmid IN (1, 10, 11, 12, 13, 3, 4, 5) THEN fmq.chemocode ELSE smc.chemocode END AS chemocode,
	fmq.consolidated_emetic_desc,
	fmq.chemodesc,
	fmq.hospicedate,
	fmq.drugsadministered,
	fmq.drugsadministereddates,
	fmq.denominatortriggerdate,
	fmq.numeratortriggerdate,
	emc.emcodes,
	fmq.health_condition,
	fmq.authrequestdate,
	fmq.authidreference,
	fmq.daysinhospice,
	fmq.ht3_desc,
	fmq.cort_desc,
	fmq.dop_desc,
	fmq.nk1_desc,
	fmq.olz_desc,
	fmq.lineofbusiness,
	fmq.clinicalscenariodescription,
	fmq.dosingdeviationtext,
	fmq.biomarkercodedescription,
	hm.ishospicemember,
	map.tin_group_1,
	map.tin_group_2,
	map.tin_group_3
FROM fact_member_quality_measures AS fmq
	LEFT JOIN dev_dtx_gc.staging.stg_emcodes_per_attributionmonth AS emc
		ON fmq.memberid = emc.memberid AND fmq.contextdate = emc.attributionmonth
	LEFT JOIN stg_member_chemotherapy AS smc
		ON fmq.memberid = smc.memberid AND fmq.contextdate = smc.attributionstartdate
	LEFT JOIN dev_dtx_gc.staging.stg_member_hospice_mapping AS hm
		ON fmq.memberid = hm.memberid AND fmq.perf_period_key = hm.perf_period_key AND fmq.lineofbusiness = hm.lineofbusiness
	LEFT JOIN dev_dtx_gc.staging.stg_client_tin_mapping AS map
		ON fmq.tin = map.tin
GROUP BY
	fmq.qmid,
	fmq.memberid,
	fmq.participatingprovidernpi,
	fmq.orderingprovidernpi,
	fmq.orderingprovider,
	fmq.perf_period_key,
	fmq.contextdate,
	fmq.episode_start_date,
	fmq.episode_end_date,
	fmq.tin,
	fmq.principalcancercode,
	fmq.cancerdiagnosisgroupcode,
	fmq.treatmentplanpathwayregimenindicatorcode,
	fmq.icd10description,
	fmq.icd10code,
	fmq.claimlinehealthservicecode,
	fmq.ipdate,
	fmq.eddate,
	CASE WHEN fmq.qmid IN (1, 10, 11, 12, 13, 3, 4, 5) THEN fmq.chemodate ELSE smc.chemodate END,
	CASE WHEN fmq.qmid IN (1, 10, 11, 12, 13, 3, 4, 5) THEN fmq.chemocode ELSE smc.chemocode END,
	fmq.consolidated_emetic_desc,
	fmq.chemodesc,
	fmq.hospicedate,
	fmq.drugsadministered,
	fmq.drugsadministereddates,
	fmq.denominatortriggerdate,
	fmq.numeratortriggerdate,
	emc.emcodes,
	fmq.health_condition,
	fmq.authrequestdate,
	fmq.authidreference,
	fmq.daysinhospice,
	fmq.ht3_desc,
	fmq.cort_desc,
	fmq.dop_desc,
	fmq.nk1_desc,
	fmq.olz_desc,
	fmq.lineofbusiness,
	fmq.clinicalscenariodescription,
	fmq.dosingdeviationtext,
	fmq.biomarkercodedescription,
	hm.ishospicemember,
	map.tin_group_1,
	map.tin_group_2,
	map.tin_group_3