-- DBT Model: stg_ic1_recon_source
-- Database: dev_dtx_gc
-- Schema: staging
-- Alias: stg_ic1_recon_source




WITH ic_payorrecon AS (

	SELECT * FROM dev_dtx_gc.IC1.PAYORICRECON
),

ic_masterepisode AS (

	SELECT * FROM dev_dtx_gc.IC1.MASTEREPISODE
),

ic_masterepisode_perfperiod AS (

	SELECT DISTINCT
		ic.*,
		pp.perf_period_name,
		REPLACE(
			REPLACE(
				pp.perf_period_name_range, pp.perf_period_name || ' : ', ''
			),
			' ',
			''
		) AS timeperioddates
	FROM ic_masterepisode AS ic
		INNER JOIN dev_dtx_gc.staging.stg_seed_performance_period AS pp
			ON
				ic.performanceperiodstartdate BETWEEN pp.perf_period_start_date AND pp.perf_period_end_date
				AND ic.performanceperiodenddate < DATEADD(YEAR, -1, TO_DATE(SYSDATE())) -- no future Perfperiods, based on the next PP will be a year from when this runs
),

payoricrecon_tin AS (
	SELECT DISTINCT
		p.*,
		m.tin AS attributedprovidertaxid
	FROM ic_payorrecon AS p
		INNER JOIN dev_dtx_gc.staging.stg_seed_reconpp2_name_tin_mapping AS m
			ON p.contractname = m.contractname
	WHERE
		p.performanceperiodstartdate NOT IN (
			SELECT DISTINCT mp.performanceperiodstartdate
			FROM ic_masterepisode_perfperiod AS mp
		)
		AND p.performanceperiodenddate < DATEADD(YEAR, -1, TO_DATE(SYSDATE())) -- no future Perfperiods, based on the next PP will be a year from when this runs
	QUALIFY
		ROW_NUMBER() OVER (
			PARTITION BY p.memberid, p.performanceperiodstartdate
			ORDER BY m.tin
		) = 1
),

payoricrecon AS (
	SELECT
		p.memberid,
		p.filerunid,
		p.contractid,
		p.lineofbusinessidentifier,
		p.administrativetaxidnumber,
		p.attributedprovidertaxid,
		p.participatingprovidernpinumber,
		p.contractstatecode,
		p.performanceperiodstartdate,
		p.performanceperiodenddate,
		p.contractperiodstartdate,
		p.contractperiodenddate,
		p.programid,
		p.providergroupingidentifier,
		p.contractname,
		p.episodecount,
		p.budgetamount,
		p.trenddescription,
		p.noveladjustmentdescription,
		p.benchmarkpriceamount,
		p.administrativediscountpercent,
		p.targetpriceamount,
		p.totalallowedactualcostamount,
		p.episodeactualtotargetdifferenceamount,
		p.sharedsavingspercent,
		p.savingspoolamount,
		p.sharedsavingsmultipliervalue,
		p.sharedsavingsexpenseamount,
		p.episodeid,
		p.patientstatename,
		p.timeperioddates,
		p.episodename,
		p.qm1code,
		COALESCE(p.qm1pointsvalue, 0) AS qm1pointsvalue,
		p.qm1performanceratevalue,
		p.qm1numeratorvalue,
		p.qm1denominatorvalue,
		p.qm2code,
		COALESCE(p.qm2pointsvalue, 0) AS qm2pointsvalue,
		p.qm2performanceratevalue,
		p.qm2numeratorvalue,
		p.qm2denominatorvalue,
		p.qm3code,
		COALESCE(p.qm3pointsvalue, 0) AS qm3pointsvalue,
		p.qm3performanceratevalue,
		p.qm3numeratorvalue,
		p.qm3denominatorvalue,
		p.qm4code,
		COALESCE(p.qm4pointsvalue, 0) AS qm4pointsvalue,
		p.qm4performanceratevalue,
		p.qm4numeratorvalue,
		p.qm4denominatorvalue,
		p.qm5code,
		COALESCE(p.qm5pointsvalue, 0) AS qm5pointsvalue,
		p.qm5performanceratevalue,
		p.qm5numeratorvalue,
		p.qm5denominatorvalue,
		p.qm6code,
		COALESCE(p.qm6pointsvalue, 0) AS qm6pointsvalue,
		p.qm6performanceratevalue,
		p.qm6numeratorvalue,
		p.qm6denominatorvalue,
		p.qm7code,
		COALESCE(p.qm7pointsvalue, 0) AS qm7pointsvalue,
		p.qm7performanceratevalue,
		p.qm7numeratorvalue,
		p.qm7denominatorvalue,
		p.qm8code,
		COALESCE(p.qm8pointsvalue, 0) AS qm8pointsvalue,
		p.qm8performanceratevalue,
		p.qm8numeratorvalue,
		p.qm8denominatorvalue,
		p.qm9code,
		COALESCE(p.qm9pointsvalue, 0) AS qm9pointsvalue,
		p.qm9performanceratevalue,
		p.qm9numeratorvalue,
		p.qm9denominatorvalue,
		p.qm10code,
		COALESCE(p.qm10pointsvalue, 0) AS qm10pointsvalue,
		p.qm10performanceratevalue,
		p.qm10numeratorvalue,
		p.qm10denominatorvalue,
		p.qm11code,
		COALESCE(p.qm11pointsvalue, 0) AS qm11pointsvalue,
		p.qm11performanceratevalue,
		p.qm11numeratorvalue,
		p.qm11denominatorvalue,
		p.qmtotalpointsvalue,
		COALESCE(p.qmaggregatequalityscorevalue, 0)
			AS qmaggregatequalityscorevalue,
		'PayorICRecon' AS datasourcetable,
        NULL AS  subscriberid,
		 NULL AS  all_other_medical,
		 NULL AS  all_other_medical_count,
		 NULL AS  amb_surg,
		 NULL AS  amb_surg_count,
		 NULL AS  attributed_oncologist,
		 NULL AS  avoid_ed_ane_allowed,
		 NULL AS  avoid_ed_ane_count,
		 NULL AS  avoid_ed_deh_allowed,
		 NULL AS  avoid_ed_deh_count,
		 NULL AS  avoid_ed_die_allowed,
		 NULL AS  avoid_ed_die_count,
		 NULL AS  avoid_ed_eme_allowed,
		 NULL AS  avoid_ed_eme_count,
		 NULL AS  avoid_ed_fev_allowed,
		 NULL AS  avoid_ed_fev_count,
		 NULL AS  avoid_ed_nau_allowed,
		 NULL AS  avoid_ed_nau_count,
		 NULL AS  avoid_ed_neu_allowed,
		 NULL AS  avoid_ed_neu_count,
		 NULL AS  avoid_ed_pai_allowed,
		 NULL AS  avoid_ed_pai_count,
		 NULL AS  avoid_ed_pne_allowed,
		 NULL AS  avoid_ed_pne_count,
		 NULL AS  avoid_ed_sep_allowed,
		 NULL AS  avoid_ed_sep_count,
		 NULL AS  avoid_ip_ane_allowed,
		 NULL AS  avoid_ip_deh_allowed,
		 NULL AS  avoid_ip_deh_count,
		 NULL AS  avoid_ip_die_allowed,
		 NULL AS  avoid_ip_die_count,
		 NULL AS  avoid_ip_eme_allowed,
		 NULL AS  avoid_ip_eme_count,
		 NULL AS  avoid_ip_fev_allowed,
		 NULL AS  avoid_ip_fev_count,
		 NULL AS  avoid_ip_nau_allowed,
		 NULL AS  avoid_ip_nau_count,
		 NULL AS  avoid_ip_neu_allowed,
		 NULL AS  avoid_ip_neu_count,
		 NULL AS  avoid_ip_pai_allowed,
		 NULL AS  avoid_ip_pai_count,
		 NULL AS  avoid_ip_pne_allowed,
		 NULL AS  avoid_ip_pne_count,
		 NULL AS  avoid_ip_sep_allowed,
		 NULL AS  avoid_ip_sep_count,
		 NULL AS  avoidable_admits_allowed,
		 NULL AS  avoidable_ed_allowed,
		 NULL AS  avoidable_ed_count,
		 NULL AS  birth_date,
		 NULL AS  ccf_paid,
		 NULL AS  chemo_allowed,
		 NULL AS  chemo_count,
		 NULL AS  chemo_drugs_medical,
		 NULL AS  chemo_drugs_medical_count,
		 NULL AS  chemotherapy_type,
		 NULL AS  dod,
		 NULL AS  ed_allowed,
		 NULL AS  ed_visits,
		 NULL AS  emergencyroomtotalvisits,
		 NULL AS  eol_chemo_allowed,
		 NULL AS  eol_chemo_count,
		 NULL AS  eol_ed_allowed,
		 NULL AS  eol_ed_visits,
		 NULL AS  eol_icu_allowed,
		 NULL AS  eol_icu_count,
		 NULL AS  episode_end_date,
		 NULL AS  episode_start_date,
		 NULL AS  er,
		 NULL AS  er_count,
		 NULL AS  gender,
		 NULL AS  home,
		 NULL AS  inpatient,
		 NULL AS  home_count,
		 NULL AS  hospice_allowed,
		 NULL AS  hospice_claim_admits,
		 NULL AS  hospice_los,
		 NULL AS  icu_allowed,
		 NULL AS  icu_claim_admits,
		 NULL AS  icu_los,
		 NULL AS  inpatient__all_other_inpatient,
		 NULL AS  inpatient__cardiology,
		 NULL AS  inpatient__detailed_coded_drugs,
		 NULL AS  inpatient__emergency_room,
		 NULL AS  inpatient__icu,
		 NULL AS  inpatient__imaging,
		 NULL AS  inpatient__lab_pathology,
		 NULL AS  inpatient__med_surg_supplies,
		 NULL AS  inpatient__operation,
		 NULL AS  inpatient__pharmacy,
		 NULL AS  inpatient__other,
		 NULL AS  inpatient__radiation_therapy,
		 NULL AS  inpatient__respiratory_pt_ot_st,
		 NULL AS  inpatient__room_and_board,
		 NULL AS  inpatient_count,
		 NULL AS  inpatient_count__all_other_inpatient,
		 NULL AS  inpatient_count__cardiology,
		 NULL AS  inpatient_count__detailed_coded_drugs,
		 NULL AS  inpatient_count__emergency_room,
		 NULL AS  inpatient_count__icu,
		 NULL AS  inpatient_count__imaging,
		 NULL AS  inpatient_count__lab_pathology,
		 NULL AS  inpatient_count__med_surg_supplies,
		 NULL AS  inpatient_count__operation,
		 NULL AS  inpatient_count__other,
		 NULL AS  inpatient_count__pharmacy,
		 NULL AS  inpatient_count__radiation_therapy,
		 NULL AS  inpatient_count__respiratory_pt_ot_st,
		 NULL AS  inpatient_count__room_and_board,
		 NULL AS  avoidable_admits_count,
		 NULL AS  inpatient_drugs_requiring_coding,
		 NULL AS  avoid_ip_ane_count,
		 NULL AS  ip_allowed,
		 NULL AS  ip_claim_admits,
		 NULL AS  ip_clusters,
		 NULL AS  ip_los,
		 NULL AS  lab,
		 NULL AS  lab_count,
		 NULL AS  min_risk_corridor,
		 NULL AS  novel_allowed,
		 NULL AS  office,
		 NULL AS  office__all_other_office,
		 NULL AS  office__cardiovascular_procedures,
		 NULL AS  office__drug_admin,
		 NULL AS  office__e_and_m,
		 NULL AS  office__radioactive_agents,
		 NULL AS  office__other,
		 NULL AS  office__radiology_mammography,
		 NULL AS  office__pathology_and_lab,
		 NULL AS  office__psychiatry,
		 NULL AS  office__radiation_treatment,
		 NULL AS  office__radiology_diagnostic,
		 NULL AS  office__radiology_guidance,
		 NULL AS  office__radiology_nuclear_medicine,
		 NULL AS  office__radiology_other,
		 NULL AS  office__radiology_rad_onc_treatment,
		 NULL AS  office__surgery,
		 NULL AS  office__therapeutic_activities,
		 NULL AS  office_count,
		 NULL AS  office_count__all_other_office,
		 NULL AS  office_count__cardiovascular_procedures,
		 NULL AS  office_count__drug_admin,
		 NULL AS  office_count__e_and_m,
		 NULL AS  office_count__other,
		 NULL AS  office_count__pathology_and_lab,
		 NULL AS  office_count__psychiatry,
		 NULL AS  office_count__radiation_treatment,
		 NULL AS  office_count__radioactive_agents,
		 NULL AS  office_count__radiology_diagnostic,
		 NULL AS  office_count__radiology_guidance,
		 NULL AS  office_count__radiology_mammography,
		 NULL AS  office_count__radiology_nuclear_medicine,
		 NULL AS  office_count__radiology_other,
		 NULL AS  office_count__radiology_rad_onc_treatment,
		 NULL AS  office_count__surgery,
		 NULL AS  office_count__therapeutic_activities,
		 NULL AS  operating_room_services_count,
		 NULL AS  outpatient,
		 NULL AS  outpatient__all_other_outpatient,
		 NULL AS  outpatient__chemo_admin,
		 NULL AS  outpatient__detailed_coded_drugs,
		 NULL AS  outpatient__gastrointestinal,
		 NULL AS  outpatient__imaging,
		 NULL AS  outpatient__iv_therapy,
		 NULL AS  outpatient__lab_pathology,
		 NULL AS  outpatient__med_surg_supplies,
		 NULL AS  outpatient__nuclear_medicine,
		 NULL AS  outpatient__operation,
		 NULL AS  outpatient__other,
		 NULL AS  outpatient__pharmacy,
		 NULL AS  outpatient__radiation_therapy,
		 NULL AS  outpatient_count,
		 NULL AS  outpatient_count__all_other_outpatient,
		 NULL AS  outpatient_count__chemo_admin,
		 NULL AS  outpatient_count__detailed_coded_drugs,
		 NULL AS  outpatient_count__gastrointestinal,
		 NULL AS  outpatient_count__imaging,
		 NULL AS  outpatient_count__iv_therapy,
		 NULL AS  outpatient_count__lab_pathology,
		 NULL AS  outpatient_count__med_surg_supplies,
		 NULL AS  outpatient_count__nuclear_medicine,
		 NULL AS  outpatient_count__operation,
		 NULL AS  outpatient_count__other,
		 NULL AS  outpatient_count__pharmacy,
		 NULL AS  outpatient_count__radiation_therapy,
		 NULL AS  practice,
		 NULL AS  prediction,
		 NULL AS  retail_pharm,
		 NULL AS  retail_pharm_count,
		 NULL AS  ssav_expns_amt_no_cap,
		 NULL AS  telehealth,
		 NULL AS  telehealth_count,
		 NULL AS  total_allowed_wind,
		 NULL AS  totalallowedamtcostall,
		 NULL AS  transportation,
		 NULL AS  transportation_count,
		 NULL AS  uc,
		 NULL AS  uc_count
	FROM payoricrecon_tin AS p
),

masterepisode AS (
	SELECT
		p.memberid,
		p.runid AS filerunid,
		p.contractid,
		p.lineofbusinessidentifier,
		p.oncologist_tin AS administrativetaxidnumber,
		p.oncologist_tin AS attributedprovidertaxid,
		p.oncologist_npi AS participatingprovidernpinumber,
		p.contractstatecode,
		p.performanceperiodstartdate,
		p.performanceperiodenddate,
		NULL AS contractperiodstartdate,
		NULL AS contractperiodenddate,
		p.pgm_id AS programid,
		p.pg_id AS providergroupingidentifier,
		p.contractname,
		p.episode_count AS episodecount,

		p.prediction_wind AS budgetamount,
		p.trend AS trenddescription,
		p.novel_adj AS noveladjustmentdescription,
		p.benchmark_price AS benchmarkpriceamount,
		p.mrc_percent AS administrativediscountpercent,
		p.target AS targetpriceamount,
		p.total_expenditures AS totalallowedactualcostamount,
		p.epsdactualtargetdiff AS episodeactualtotargetdifferenceamount,
		p.ssprct AS sharedsavingspercent,
		p.savings_pool AS savingspoolamount,
		p.quality_multiplier AS sharedsavingsmultipliervalue,
		p.ssav_expns_amt AS sharedsavingsexpenseamount,
		p.episodeid,
		p.member_state AS patientstatename,
		p.timeperioddates,
		p.cancer_type AS episodename,

		p.qm1code,
		COALESCE(p.qm1pointsvalue, 0) AS qm1pointsvalue,
		p.qm1performanceratevalue,
		p.qm1numeratorvalue,
		p.qm1denominatorvalue,
		p.qm2code,
		COALESCE(p.qm2pointsvalue, 0) AS qm2pointsvalue,
		p.qm2performanceratevalue,
		p.qm2numeratorvalue,
		p.qm2denominatorvalue,
		p.qm3code,
		COALESCE(p.qm3pointsvalue, 0) AS qm3pointsvalue,
		p.qm3performanceratevalue,
		p.qm3numeratorvalue,
		p.qm3denominatorvalue,
		p.qm4code,
		COALESCE(p.qm4pointsvalue, 0) AS qm4pointsvalue,
		p.qm4performanceratevalue,
		p.qm4numeratorvalue,
		p.qm4denominatorvalue,
		p.qm5code,
		COALESCE(p.qm5pointsvalue, 0) AS qm5pointsvalue,
		p.qm5performanceratevalue,
		p.qm5numeratorvalue,
		p.qm5denominatorvalue,
		p.qm6code,
		COALESCE(p.qm6pointsvalue, 0) AS qm6pointsvalue,
		p.qm6performanceratevalue,
		p.qm6numeratorvalue,
		p.qm6denominatorvalue,
		p.qm7code,
		COALESCE(p.qm7pointsvalue, 0) AS qm7pointsvalue,
		p.qm7performanceratevalue,
		p.qm7numeratorvalue,
		p.qm7denominatorvalue,
		p.qm8code,
		COALESCE(p.qm8pointsvalue, 0) AS qm8pointsvalue,
		p.qm8performanceratevalue,
		p.qm8numeratorvalue,
		p.qm8denominatorvalue,
		p.qm9code,
		COALESCE(p.qm9pointsvalue, 0) AS qm9pointsvalue,
		p.qm9performanceratevalue,
		p.qm9numeratorvalue,
		p.qm9denominatorvalue,
		p.qm10code,
		COALESCE(p.qm10pointsvalue, 0) AS qm10pointsvalue,
		p.qm10performanceratevalue,
		p.qm10numeratorvalue,
		p.qm10denominatorvalue,
		p.qm11code,
		COALESCE(p.qm11pointsvalue, 0) AS qm11pointsvalue,
		p.qm11performanceratevalue,
		p.qm11numeratorvalue,
		p.qm11denominatorvalue,
		p.qmtotalpointsvalue,
		COALESCE(p.qmaggregatequalityscorevalue, 0)
			AS qmaggregatequalityscorevalue,
		'MasterEpisode' AS datasourcetable,
		p.subscriberid,
		p.all_other_medical,
		p.all_other_medical_count,
		p.amb_surg,
		p.amb_surg_count,
		p.attributed_oncologist,
		p.avoid_ed_ane_allowed,
		p.avoid_ed_ane_count,
		p.avoid_ed_deh_allowed,
		p.avoid_ed_deh_count,
		p.avoid_ed_die_allowed,
		p.avoid_ed_die_count,
		p.avoid_ed_eme_allowed,
		p.avoid_ed_eme_count,
		p.avoid_ed_fev_allowed,
		p.avoid_ed_fev_count,
		p.avoid_ed_nau_allowed,
		p.avoid_ed_nau_count,
		p.avoid_ed_neu_allowed,
		p.avoid_ed_neu_count,
		p.avoid_ed_pai_allowed,
		p.avoid_ed_pai_count,
		p.avoid_ed_pne_allowed,
		p.avoid_ed_pne_count,
		p.avoid_ed_sep_allowed,
		p.avoid_ed_sep_count,
		p.avoid_ip_ane_allowed,
		p.avoid_ip_deh_allowed,
		p.avoid_ip_deh_count,
		p.avoid_ip_die_allowed,
		p.avoid_ip_die_count,
		p.avoid_ip_eme_allowed,
		p.avoid_ip_eme_count,
		p.avoid_ip_fev_allowed,
		p.avoid_ip_fev_count,
		p.avoid_ip_nau_allowed,
		p.avoid_ip_nau_count,
		p.avoid_ip_neu_allowed,
		p.avoid_ip_neu_count,
		p.avoid_ip_pai_allowed,
		p.avoid_ip_pai_count,
		p.avoid_ip_pne_allowed,
		p.avoid_ip_pne_count,
		p.avoid_ip_sep_allowed,
		p.avoid_ip_sep_count,
		p.avoidable_admits_allowed,
		p.avoidable_ed_allowed,
		p.avoidable_ed_count,
		p.birth_date,
		p.ccf_paid,
		p.chemo_allowed,
		p.chemo_count,
		p.chemo_drugs_medical,
		p.chemo_drugs_medical_count,
		p.chemotherapy_type,
		p.dod,
		p.ed_allowed,
		p.ed_visits,
		p.emergencyroomtotalvisits,
		p.eol_chemo_allowed,
		p.eol_chemo_count,
		p.eol_ed_allowed,
		p.eol_ed_visits,
		p.eol_icu_allowed,
		p.eol_icu_count,
		p.episode_end_date,
		p.episode_start_date,
		p.er,
		p.er_count,
		p.gender,
		p.home,
		p.inpatient,
		p.home_count,
		p.hospice_allowed,
		p.hospice_claim_admits,
		p.hospice_los,
		p.icu_allowed,
		p.icu_claim_admits,
		p.icu_los,
		p.inpatient__all_other_inpatient,
		p.inpatient__cardiology,
		p.inpatient__detailed_coded_drugs,
		p.inpatient__emergency_room,
		p.inpatient__icu,
		p.inpatient__imaging,
		p.inpatient__lab_pathology,
		p.inpatient__med_surg_supplies,
		p.inpatient__operation,
		p.inpatient__pharmacy,
		p.inpatient__other,
		p.inpatient__radiation_therapy,
		p.inpatient__respiratory_pt_ot_st,
		p.inpatient__room_and_board,
		p.inpatient_count,
		p.inpatient_count__all_other_inpatient,
		p.inpatient_count__cardiology,
		p.inpatient_count__detailed_coded_drugs,
		p.inpatient_count__emergency_room,
		p.inpatient_count__icu,
		p.inpatient_count__imaging,
		p.inpatient_count__lab_pathology,
		p.inpatient_count__med_surg_supplies,
		p.inpatient_count__operation,
		p.inpatient_count__other,
		p.inpatient_count__pharmacy,
		p.inpatient_count__radiation_therapy,
		p.inpatient_count__respiratory_pt_ot_st,
		p.inpatient_count__room_and_board,
		p.avoidable_admits_count,
		p.inpatient_drugs_requiring_coding,
		p.avoid_ip_ane_count,
		p.ip_allowed,
		p.ip_claim_admits,
		p.ip_clusters,
		p.ip_los,
		p.lab,
		p.lab_count,
		p.min_risk_corridor,
		p.novel_allowed,
		p.office,
		p.office__all_other_office,
		p.office__cardiovascular_procedures,
		p.office__drug_admin,
		p.office__e_and_m,
		p.office__radioactive_agents,
		p.office__other,
		p.office__radiology_mammography,
		p.office__pathology_and_lab,
		p.office__psychiatry,
		p.office__radiation_treatment,
		p.office__radiology_diagnostic,
		p.office__radiology_guidance,
		p.office__radiology_nuclear_medicine,
		p.office__radiology_other,
		p.office__radiology_rad_onc_treatment,
		p.office__surgery,
		p.office__therapeutic_activities,
		p.office_count,
		p.office_count__all_other_office,
		p.office_count__cardiovascular_procedures,
		p.office_count__drug_admin,
		p.office_count__e_and_m,
		p.office_count__other,
		p.office_count__pathology_and_lab,
		p.office_count__psychiatry,
		p.office_count__radiation_treatment,
		p.office_count__radioactive_agents,
		p.office_count__radiology_diagnostic,
		p.office_count__radiology_guidance,
		p.office_count__radiology_mammography,
		p.office_count__radiology_nuclear_medicine,
		p.office_count__radiology_other,
		p.office_count__radiology_rad_onc_treatment,
		p.office_count__surgery,
		p.office_count__therapeutic_activities,
		p.operating_room_services_count,
		p.outpatient,
		p.outpatient__all_other_outpatient,
		p.outpatient__chemo_admin,
		p.outpatient__detailed_coded_drugs,
		p.outpatient__gastrointestinal,
		p.outpatient__imaging,
		p.outpatient__iv_therapy,
		p.outpatient__lab_pathology,
		p.outpatient__med_surg_supplies,
		p.outpatient__nuclear_medicine,
		p.outpatient__operation,
		p.outpatient__other,
		p.outpatient__pharmacy,
		p.outpatient__radiation_therapy,
		p.outpatient_count,
		p.outpatient_count__all_other_outpatient,
		p.outpatient_count__chemo_admin,
		p.outpatient_count__detailed_coded_drugs,
		p.outpatient_count__gastrointestinal,
		p.outpatient_count__imaging,
		p.outpatient_count__iv_therapy,
		p.outpatient_count__lab_pathology,
		p.outpatient_count__med_surg_supplies,
		p.outpatient_count__nuclear_medicine,
		p.outpatient_count__operation,
		p.outpatient_count__other,
		p.outpatient_count__pharmacy,
		p.outpatient_count__radiation_therapy,
		p.practice,
		p.prediction,
		p.retail_pharm,
		p.retail_pharm_count,
		p.ssav_expns_amt_no_cap,
		p.telehealth,
		p.telehealth_count,
		p.total_allowed_wind,
		p.totalallowedamtcostall,
		p.transportation,
		p.transportation_count,
		p.uc,
		p.uc_count
	FROM ic_masterepisode_perfperiod AS p

),

all_recon_sources AS (

	SELECT * FROM payoricrecon
	UNION ALL
	SELECT * FROM masterepisode
)

SELECT
	p.filerunid,
	p.contractid,
	p.lineofbusinessidentifier,
	p.administrativetaxidnumber,
	p.attributedprovidertaxid,
	p.participatingprovidernpinumber,
	p.contractstatecode,
	p.performanceperiodstartdate,
	p.performanceperiodenddate,
	p.contractperiodstartdate,
	p.contractperiodenddate,
	p.programid,
	p.providergroupingidentifier,
	p.contractname,
	p.episodecount,
	p.budgetamount,

	p.trenddescription,
	p.noveladjustmentdescription,
	p.benchmarkpriceamount,
	p.administrativediscountpercent,
	p.targetpriceamount,
	p.totalallowedactualcostamount,
	p.episodeactualtotargetdifferenceamount,
	p.sharedsavingspercent,
	p.savingspoolamount,
	p.sharedsavingsmultipliervalue,
	p.sharedsavingsexpenseamount,
	p.episodeid,
	p.patientstatename,
	p.timeperioddates,
	p.episodename,
	p.qm1code,

	p.qm1numeratorvalue,
	p.qm1denominatorvalue,
	p.qm2code,
	p.qm2numeratorvalue,
	p.qm2denominatorvalue,
	p.qm3code,
	p.qm3numeratorvalue,
	p.qm3denominatorvalue,
	p.qm4code,
	p.qm4numeratorvalue,
	p.qm4denominatorvalue,
	p.qm5code,
	p.qm5numeratorvalue,
	p.qm5denominatorvalue,
	p.qm6code,
	p.qm6numeratorvalue,
	p.qm6denominatorvalue,
	p.qm7code,
	p.qm7numeratorvalue,
	p.qm7denominatorvalue,
	p.qm8code,
	p.qm8numeratorvalue,
	p.qm8denominatorvalue,
	p.qm9code,
	p.qm9numeratorvalue,
	p.qm9denominatorvalue,
	p.qm10code,
	p.qm10numeratorvalue,
	p.qm10denominatorvalue,
	p.qm11code,
	p.qm11numeratorvalue,
	p.qm11denominatorvalue,
	p.qmtotalpointsvalue,
	p.datasourcetable,
	CAST(p.memberid AS number(38, 0)) AS memberid,
	COALESCE(p.qm1pointsvalue, 0) AS qm1pointsvalue,
	IFF(
		p.qm1performanceratevalue > 1,
		p.qm1performanceratevalue / 100,
		p.qm1performanceratevalue
	) AS qm1performanceratevalue,
	COALESCE(p.qm2pointsvalue, 0) AS qm2pointsvalue,
	IFF(
		p.qm2performanceratevalue > 1,
		p.qm2performanceratevalue / 100,
		p.qm2performanceratevalue
	) AS qm2performanceratevalue,
	COALESCE(p.qm3pointsvalue, 0) AS qm3pointsvalue,
	IFF(
		p.qm3performanceratevalue > 1,
		p.qm3performanceratevalue / 100,
		p.qm3performanceratevalue
	) AS qm3performanceratevalue,
	COALESCE(p.qm4pointsvalue, 0) AS qm4pointsvalue,
	IFF(
		p.qm4performanceratevalue > 1,
		p.qm4performanceratevalue / 100,
		p.qm4performanceratevalue
	) AS qm4performanceratevalue,
	COALESCE(p.qm5pointsvalue, 0) AS qm5pointsvalue,
	IFF(
		p.qm5performanceratevalue > 1,
		p.qm5performanceratevalue / 100,
		p.qm5performanceratevalue
	) AS qm5performanceratevalue,
	COALESCE(p.qm6pointsvalue, 0) AS qm6pointsvalue,
	IFF(
		p.qm6performanceratevalue > 1,
		p.qm6performanceratevalue / 100,
		p.qm6performanceratevalue
	) AS qm6performanceratevalue,
	COALESCE(p.qm7pointsvalue, 0) AS qm7pointsvalue,
	IFF(
		p.qm7performanceratevalue > 1,
		p.qm7performanceratevalue / 100,
		p.qm7performanceratevalue
	) AS qm7performanceratevalue,
	COALESCE(p.qm8pointsvalue, 0) AS qm8pointsvalue,
	IFF(
		p.qm8performanceratevalue > 1,
		p.qm8performanceratevalue / 100,
		p.qm8performanceratevalue
	) AS qm8performanceratevalue,
	COALESCE(p.qm9pointsvalue, 0) AS qm9pointsvalue,
	IFF(
		p.qm9performanceratevalue > 1,
		p.qm9performanceratevalue / 100,
		p.qm9performanceratevalue
	) AS qm9performanceratevalue,
	COALESCE(p.qm10pointsvalue, 0) AS qm10pointsvalue,
	IFF(
		p.qm10performanceratevalue > 1,
		p.qm10performanceratevalue / 100,
		p.qm10performanceratevalue
	) AS qm10performanceratevalue,
	COALESCE(p.qm11pointsvalue, 0) AS qm11pointsvalue,
	IFF(
		p.qm11performanceratevalue > 1,
		p.qm11performanceratevalue / 100,
		p.qm11performanceratevalue
	) AS qm11performanceratevalue,
	COALESCE(p.qmaggregatequalityscorevalue, 0) AS qmaggregatequalityscorevalue,
		p.subscriberid,
		p.all_other_medical,
		p.all_other_medical_count,
		p.amb_surg,
		p.amb_surg_count,
		p.attributed_oncologist,
		p.avoid_ed_ane_allowed,
		p.avoid_ed_ane_count,
		p.avoid_ed_deh_allowed,
		p.avoid_ed_deh_count,
		p.avoid_ed_die_allowed,
		p.avoid_ed_die_count,
		p.avoid_ed_eme_allowed,
		p.avoid_ed_eme_count,
		p.avoid_ed_fev_allowed,
		p.avoid_ed_fev_count,
		p.avoid_ed_nau_allowed,
		p.avoid_ed_nau_count,
		p.avoid_ed_neu_allowed,
		p.avoid_ed_neu_count,
		p.avoid_ed_pai_allowed,
		p.avoid_ed_pai_count,
		p.avoid_ed_pne_allowed,
		p.avoid_ed_pne_count,
		p.avoid_ed_sep_allowed,
		p.avoid_ed_sep_count,
		p.avoid_ip_ane_allowed,
		p.avoid_ip_deh_allowed,
		p.avoid_ip_deh_count,
		p.avoid_ip_die_allowed,
		p.avoid_ip_die_count,
		p.avoid_ip_eme_allowed,
		p.avoid_ip_eme_count,
		p.avoid_ip_fev_allowed,
		p.avoid_ip_fev_count,
		p.avoid_ip_nau_allowed,
		p.avoid_ip_nau_count,
		p.avoid_ip_neu_allowed,
		p.avoid_ip_neu_count,
		p.avoid_ip_pai_allowed,
		p.avoid_ip_pai_count,
		p.avoid_ip_pne_allowed,
		p.avoid_ip_pne_count,
		p.avoid_ip_sep_allowed,
		p.avoid_ip_sep_count,
		p.avoidable_admits_allowed,
		p.avoidable_ed_allowed,
		p.avoidable_ed_count,
		p.birth_date,
		p.ccf_paid,
		p.chemo_allowed,
		p.chemo_count,
		p.chemo_drugs_medical,
		p.chemo_drugs_medical_count,
		p.chemotherapy_type,
		p.dod,
		p.ed_allowed,
		p.ed_visits,
		p.emergencyroomtotalvisits,
		p.eol_chemo_allowed,
		p.eol_chemo_count,
		p.eol_ed_allowed,
		p.eol_ed_visits,
		p.eol_icu_allowed,
		p.eol_icu_count,
		p.episode_end_date,
		p.episode_start_date,
		p.er,
		p.er_count,
		p.gender,
		p.home,
		p.inpatient,
		p.home_count,
		p.hospice_allowed,
		p.hospice_claim_admits,
		p.hospice_los,
		p.icu_allowed,
		p.icu_claim_admits,
		p.icu_los,
		p.inpatient__all_other_inpatient,
		p.inpatient__cardiology,
		p.inpatient__detailed_coded_drugs,
		p.inpatient__emergency_room,
		p.inpatient__icu,
		p.inpatient__imaging,
		p.inpatient__lab_pathology,
		p.inpatient__med_surg_supplies,
		p.inpatient__operation,
		p.inpatient__pharmacy,
		p.inpatient__other,
		p.inpatient__radiation_therapy,
		p.inpatient__respiratory_pt_ot_st,
		p.inpatient__room_and_board,
		p.inpatient_count,
		p.inpatient_count__all_other_inpatient,
		p.inpatient_count__cardiology,
		p.inpatient_count__detailed_coded_drugs,
		p.inpatient_count__emergency_room,
		p.inpatient_count__icu,
		p.inpatient_count__imaging,
		p.inpatient_count__lab_pathology,
		p.inpatient_count__med_surg_supplies,
		p.inpatient_count__operation,
		p.inpatient_count__other,
		p.inpatient_count__pharmacy,
		p.inpatient_count__radiation_therapy,
		p.inpatient_count__respiratory_pt_ot_st,
		p.inpatient_count__room_and_board,
		p.avoidable_admits_count,
		p.inpatient_drugs_requiring_coding,
		p.avoid_ip_ane_count,
		p.ip_allowed,
		p.ip_claim_admits,
		p.ip_clusters,
		p.ip_los,
		p.lab,
		p.lab_count,
		p.min_risk_corridor,
		p.novel_allowed,
		p.office,
		p.office__all_other_office,
		p.office__cardiovascular_procedures,
		p.office__drug_admin,
		p.office__e_and_m,
		p.office__radioactive_agents,
		p.office__other,
		p.office__radiology_mammography,
		p.office__pathology_and_lab,
		p.office__psychiatry,
		p.office__radiation_treatment,
		p.office__radiology_diagnostic,
		p.office__radiology_guidance,
		p.office__radiology_nuclear_medicine,
		p.office__radiology_other,
		p.office__radiology_rad_onc_treatment,
		p.office__surgery,
		p.office__therapeutic_activities,
		p.office_count,
		p.office_count__all_other_office,
		p.office_count__cardiovascular_procedures,
		p.office_count__drug_admin,
		p.office_count__e_and_m,
		p.office_count__other,
		p.office_count__pathology_and_lab,
		p.office_count__psychiatry,
		p.office_count__radiation_treatment,
		p.office_count__radioactive_agents,
		p.office_count__radiology_diagnostic,
		p.office_count__radiology_guidance,
		p.office_count__radiology_mammography,
		p.office_count__radiology_nuclear_medicine,
		p.office_count__radiology_other,
		p.office_count__radiology_rad_onc_treatment,
		p.office_count__surgery,
		p.office_count__therapeutic_activities,
		p.operating_room_services_count,
		p.outpatient,
		p.outpatient__all_other_outpatient,
		p.outpatient__chemo_admin,
		p.outpatient__detailed_coded_drugs,
		p.outpatient__gastrointestinal,
		p.outpatient__imaging,
		p.outpatient__iv_therapy,
		p.outpatient__lab_pathology,
		p.outpatient__med_surg_supplies,
		p.outpatient__nuclear_medicine,
		p.outpatient__operation,
		p.outpatient__other,
		p.outpatient__pharmacy,
		p.outpatient__radiation_therapy,
		p.outpatient_count,
		p.outpatient_count__all_other_outpatient,
		p.outpatient_count__chemo_admin,
		p.outpatient_count__detailed_coded_drugs,
		p.outpatient_count__gastrointestinal,
		p.outpatient_count__imaging,
		p.outpatient_count__iv_therapy,
		p.outpatient_count__lab_pathology,
		p.outpatient_count__med_surg_supplies,
		p.outpatient_count__nuclear_medicine,
		p.outpatient_count__operation,
		p.outpatient_count__other,
		p.outpatient_count__pharmacy,
		p.outpatient_count__radiation_therapy,
		p.practice,
		p.prediction,
		p.retail_pharm,
		p.retail_pharm_count,
		p.ssav_expns_amt_no_cap,
		p.telehealth,
		p.telehealth_count,
		p.total_allowed_wind,
		p.totalallowedamtcostall,
		p.transportation,
		p.transportation_count,
		p.uc,
		p.uc_count
FROM all_recon_sources AS p