# Minimal Docker Compose - Quickest setup
version: '3.8'

services:
  rag-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data:ro
      - ./config.yaml:/app/config.yaml:ro
    environment:
      - PYTHONPATH=/app/src

# Usage: docker-compose -f docker-compose.minimal.yml up --build